<?php

namespace Solucel\AdminBundle\Repository;

/**
 * AdminSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
