<?php

namespace Solucel\AdminBundle\Repository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends \Doctrine\ORM\EntityRepository
{
	
	

	
	public function getFilteredAgencies($userFilters){
		
/*
		 $qb = $this->createQueryBuilder('a');
		 $qb->select('a')
		 	//->addSelect('o')
		 	//->from('Solucel\AdminBundle\Entity\User', 'u')
		    //->join('a.operator', 'o')
			->andWhere('a.enabled = 1');
			

			if($userFilters["operator_id"] != NULL){
				$qb->andWhere('a.operator = '.intval($userFilters["operator_id"]));	
			}
		    
		return $qb;	
 * 
 */
		
		$strFilter = "";
		if($userFilters["operator_id"] != NULL){
			$strFilter = " AND o.id =  ".intval($userFilters["operator_id"]);					
		}
 
  
		$sql = "	SELECT 	a.id id, a.name name, a.enabled,
							o.id operatorID, o.name operator 
					FROM	agency a
						INNER JOIN operator o ON (o.id = a.operator_id)
					WHERE 	a.enabled = 1 
					{$strFilter}";
	
					 
		//print $sql;die;
		   
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();
	    				   

		return $execute;		 
		
			
		
	}	
	
		
}
