<?php

namespace Solucel\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
	
	

	public function getInfo(){
		/*
        'client.name' => 'Name',
		'client.lastName' => 'LastName',
        'client.dpi' => 'Dpi',
        'client.phone' => 'Phone',
		'client.contactPhone' => 'ContactPhone', 
        'client.clientType' => 'ClientType',
        'client.enabled' => 'Enabled',
        'client.id'   => 'Actions',
		 * 
		 */			
	
		//u.username
        $qb = $this->createQueryBuilder('client');
				
		$qb->select("client.name, client.lastName, client.dpi, client.enabled, client.id, client.phone, client.contactPhone, client.clientType");

		return $qb;	
		
			
		
	}	
	
	
	public function findClient($term){

		$sql = "	SELECT 	*
					FROM	client
					WHERE	(name LIKE '%".$term."%' OR last_name LIKE '%".$term."%')
					AND		enabled = 1";
					 
		   
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();		   
		
		$clients = array();
        foreach ($execute as $entity)
        {
            //$clients[] = $entity["name"];
            array_push($clients, array('value'=>$entity["name"]." ".$entity["last_name"]." - dpi:".$entity["dpi"], 'id'=> $entity["id"],
										'client_code' =>$entity["client_code"], 'name' =>$entity["name"], 'last_name' =>$entity["last_name"],
										'nit' =>$entity["nit"], 'dpi' =>$entity["dpi"], 'phone' =>$entity["phone"], 'client_type' => $entity["client_type"],
										'contact_phone' =>$entity["contact_phone"], 'email' =>$entity["email"], 'state_id' =>$entity["state_id"]
										));
        }
		
		return $clients;

	}


    public function getRequiredDTData($start, $length, $orders, $search, $columns)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');




        //ENABLED
        $query->andWhere("u.enabled = 1");
        $countQuery->andWhere("u.enabled = 1");
        //$query->andWhere("r.enabled = 1");
        //$countQuery->andWhere("r.enabled = 1");



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'u.id ='. $searchItem;
                        break;
                    }
                    case 'name':
                    {
                        $searchQuery = 'u.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'lastName':
                    {
                        $searchQuery = 'u.lastName LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'dpi':
                    {
                        $searchQuery = 'u.dpi LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'phone':
                    {
                        $searchQuery = 'u.phone LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'u.id';
                        break;
                    }

                    case 'name':
                    {
                        $orderColumn = 'u.name';
                        break;
                    }

                    case 'lastName':
                    {
                        $orderColumn = 'u.lastName';
                        break;
                    }

                    case 'dpi':
                    {
                        $orderColumn = 'u.dpi';
                        break;
                    }

                    case 'phone':
                    {
                        $orderColumn = 'u.phone';
                        break;
                    }
                    case 'enabled':
                    {
                        $orderColumn = 'u.enabled';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }



}
