<?php

namespace Solucel\AdminBundle\Repository;

/**
 * DeviceReplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceReplacementRepository extends \Doctrine\ORM\EntityRepository
{
	

	public function getAjaxList(){


		 $qb = $this->createQueryBuilder('r');
		 $qb->select('r')
		 	->addSelect('b')
			->addSelect('m')

		    ->join('r.deviceBrand', 'b')
			->join('r.deviceModel', 'm')
			;
			//->andWhere('u.enabled = 1');
			//filter brand
		return $qb;



	}



    public function getRequiredDTData($start, $length, $orders, $search, $columns)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');

        //joins
        $query->join('u.deviceBrand', 'b');
        $query->join('u.deviceModel', 'm');

        $countQuery->join('u.deviceBrand', 'b');
        $countQuery->join('u.deviceModel', 'm');


        //ENABLED


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'u.id ='. $searchItem;
                        break;
                    }
                    case 'name':
                    {
                        $searchQuery = 'u.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'code':
                    {
                        $searchQuery = 'u.replacementCode LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'brand':
                    {
                        $searchQuery = 'b.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'model':
                    {
                        $searchQuery = 'm.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'u.id';
                        break;
                    }

                    case 'name':
                    {
                        $orderColumn = 'u.name';
                        break;
                    }

                    case 'code':
                    {
                        $orderColumn = 'u.replacementCode';
                        break;
                    }

                    case 'brand':
                    {
                        $orderColumn = 'b.name';
                        break;
                    }

                    case 'model':
                    {
                        $orderColumn = 'm.name';
                        break;
                    }


                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }


}
