<?php

namespace Solucel\AdminBundle\Repository;

/**
 * LoginLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginLogRepository extends \Doctrine\ORM\EntityRepository
{


    // Get the total number of elements
    public function count(array $criteria)
    {
        return $this
            ->createQueryBuilder('object')
            ->select("count(object.id)")
            ->getQuery()
            ->getSingleScalarResult();
    }


    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('sl');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('sl');
        $countQuery->select('COUNT(sl)');

        // Create inner joins
        $query->join('sl.user', 'u');
        $countQuery->join('sl.user', 'u');


        // Other conditions than the ones sent by the Ajax call ?
        if ($otherConditions === null)
        {
            // No
            // However, add a "always true" condition to keep an uniform treatment in all cases
            $query->where("1=1");
            $countQuery->where("1=1");
        }
        else
        {
            // Add date condition
            $query->where('sl.createdAt BETWEEN :startDate AND :endDate')
                ->setParameter('startDate', $otherConditions["start"])
                ->setParameter('endDate', $otherConditions["end"]);
            //$countQuery->where($otherConditions);
            $countQuery->where('sl.createdAt BETWEEN :startDate AND :endDate')
                ->setParameter('startDate', $otherConditions["start"])
                ->setParameter('endDate', $otherConditions["end"]);


        }

        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                // $column['name'] is the name of the column as sent by the JS
                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'sl.id ='. $searchItem;
                        break;
                    }
                    case 'username':
                    {
                        $searchQuery = 'u.username LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'action':
                    {
                        $searchQuery = 'sl.action LIKE \'%'.$searchItem.'%\'';
                        break;
                    }


                    //created_at DOES NOT APPLY

                }

                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        foreach ($orders as $key => $order)
        {
            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'sl.id';
                        break;
                    }
                    case 'username':
                    {
                        $orderColumn = 'u.username';
                        break;
                    }
                    case 'action':
                    {
                        $orderColumn = 'sl.action';
                        break;
                    }

                    case 'created_at':
                    {
                        $orderColumn = 'sl.createdAt';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }

        // Execute
        //print $query->getSQL();die;
        /*
        $query = $query->getQuery();
        // string
        $sql = $query->getSQL();
        print "<pre>";
        print $sql;
        var_dump($query->getParameters());die;
        */


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
}
