<?php

namespace Solucel\AdminBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	

	public function getNotificationsCount($userID){
		
		
		$sql = "	SELECT 	COUNT(n.id) count
					FROM 	notification n
					WHERE 	enabled = 1
					AND 	already_read = 0 
					AND 	user_id = {$userID}";
					//AND 	( DATE(now()) >= DATE(n.registration_date) AND DATE(now()) <= DATE(n.expiration_date) )
					
				
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $return = $stmt->fetchAll();
		//var_dump($return[0]["count"]);die;					
		return intval($return[0]["count"]);
		
	}	
	
	
	public function getNotificationsDetail($userID){

		
		
		$sql = "	SELECT 	n.id, n.name, n.description, n.already_read alreadyRead, n.created_at createdAt,
							u.username createdBy
					FROM 	notification n
						INNER JOIN user u ON (u.id = n.created_by)
					WHERE 	n.enabled = 1
					AND 	user_id = {$userID}
					AND 	already_read = 0";
					
					//AND ( DATE(now()) >= DATE(n.registration_date) AND DATE(now()) <= DATE(n.expiration_date) ) ".$aux." ORDER 	BY n.already_read, n.registration_date
					
				
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    return $stmt->fetchAll();					
		
		
	}	
	
	
	public function getNotificationByUser($userID){
		//u.username
        $qb = $this->createQueryBuilder('n');
		$qb->select('n.id, n.createdAt, n.description, n.name, u.username' );
		
		//$qb->innerJoin( 'n.shipperStaffDepartment', 'dep', 'WITH', 'dep.id = n.shipperStaffDepartment');
		$qb->innerJoin('n.user', 'u', 'WITH','u.id = n.user');
		$and_cond = $qb->expr()->andx();
		$and_cond->add($qb->expr()->eq('n.user', $userID));
		$qb->andWhere($and_cond);
		$qb->andWhere("n.enabled = 1");	
        //OJO NO APLICAR ORDER BY EN DATATABLES AJAX, por que hace inutil el sort
        
		return $qb;	

		
	}
		
	
	
}
