<?php

namespace Solucel\AdminBundle\Repository;

/**
 * ServiceCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
