<?php

namespace Solucel\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{



    public function getRequiredDTData($start, $length, $orders, $search, $columns)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');

        // Create inner joins
        $query->join('u.role', 'r');
        $countQuery->join('u.role', 'r');

        //ENABLED
        $query->andWhere("u.enabled = 1");
        $countQuery->andWhere("u.enabled = 1");


        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'u.id = '. $searchItem;
                        break;
                    }

                    case 'name':
                    {
                        $searchQuery = 'u.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'username':
                    {
                        $searchQuery = 'u.username LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'email':
                    {
                        $searchQuery = 'u.email LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'role':
                    {
                        $searchQuery = 'r.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }



        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'u.id';
                        break;
                    }

                    case 'name':
                    {
                        $orderColumn = 'u.name';
                        break;
                    }

                    case 'username':
                    {
                        $orderColumn = 'u.username';
                        break;
                    }

                    case 'email':
                    {
                        $orderColumn = 'u.email';
                        break;
                    }

                    case 'role':
                    {
                        $orderColumn = 'r.name';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }

	
	public function getUserFilters($userID, $levelID){
		//die;
		
		$strFilter = "";
		if($levelID != 0){
			$strFilter = " AND sc.id = $levelID";
		}
		
		
			$sql = "	SELECT 	brand.id brand_id, brand.name brand_name, 
								sc.id center_id, sc.name center_name,
								o.id operator_id, o.name operator_name
								
						FROM	user u
							LEFT JOIN device_brand brand ON ( u.device_brand_id = brand.id )
							LEFT JOIN service_center sc ON ( u.service_center_id = sc.id )
							LEFT JOIN operator o ON ( u.operator_id = o.id )
						
						WHERE		u.enabled = 1 
						{$strFilter}";
						//WHERE	u.id = '{$id}'
	
					 
		   
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();
	    				   

		return $execute[0];		
		
		
	}


	public function myFilter($filterOperator, $filterBrand){

        $strFilter = "";

        if($filterOperator != 0){
            $strFilter .= " AND ro.operator_id =  {$filterOperator} ";
        }
        if($filterBrand != 0){
            $strFilter .= " AND ro.device_brand_id =  {$filterBrand} ";
        }

        return $strFilter;
    }

    public function getTopByOrders($from, $to, $filterOperator, $filterBrand){

        $strFilter = $this->myFilter($filterOperator, $filterBrand);

        //u.username tech_name
        $sql = "    SELECT COUNT(DISTINCT(ro.id)) orders, u.id tech_id, CONCAT(u.name, ' ', u.last_name ) tech_name
                    FROM	repair_order ro
                        INNER JOIN repair_order_fix rof ON(ro.id = rof.repair_order_id)
                        INNER JOIN user u ON(rof.assigned_to = u.id)
                        INNER JOIN repair_order_status ros ON(ros.repair_order_id = ro.id 
                            AND ros.repair_status_id = 10)	
                    WHERE	u.role_id = 7
                    AND     (DATE(ro.created_at) >= '{$from}' AND DATE(ro.created_at) <= '{$to}')
                    {$strFilter}
                    GROUP BY u.id
                    ORDER BY orders DESC 
                    LIMIT 30";

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        if(!empty($execute)){
            return $execute;
        }
        else{
            return array();
        }


    }



    public function getOrdersByLevel($from, $to, $arrTechs, $filterOperator, $filterBrand){

        $strFilter = $this->myFilter($filterOperator, $filterBrand);

        if(!empty($arrTechs)){

            $strTechs = implode(",", $arrTechs);

            $sql = "SELECT	COUNT(ro.id) orders, u.id tech_id, CONCAT(u.name, ' ', u.last_name ) tech_name, 
                                 CONCAT('Nivel ', dfl.name) level_name, dfl.id level_id
                    FROM	repair_order ro
                        INNER JOIN repair_order_status ros ON(ros.repair_order_id = ro.id 
                            AND ros.repair_status_id = 10)      
                        INNER JOIN repair_order_fix rof ON(ro.id = rof.repair_order_id)
                        INNER JOIN user u ON(rof.assigned_to = u.id)
                                          
                        INNER JOIN repair_order_device_fix_type rft ON (ro.id = rft.repair_order_id)
                        INNER JOIN device_fix_type dft ON(dft.id = rft.device_fix_type_id)
                        INNER JOIN device_fix_level dfl ON(dfl.id = dft.device_fix_level_id)
                    WHERE       u.id IN($strTechs)
                    AND         (DATE(ro.created_at) >= '{$from}' AND DATE(ro.created_at) <= '{$to}')
                    {$strFilter}
                    GROUP BY u.id, dfl.id
                    ORDER BY u.id, dfl.name, orders DESC

            ";


            //print $sql;die;

            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute();

            $execute = $stmt->fetchAll();

            if(!empty($execute)){

                $arrGroupTechs = array();

                foreach ($execute as $row){
                    $techID = $row["tech_id"];

                    if(!isset($arrGroupTechs[$techID])){
                        $arrGroupTechs[$techID] = array();
                        //$arrGroupTechs[$techID]["dealer"] = $row["tech_name"];

                    }

                    $levelID = intval($row["level_id"]);
                    $arrGroupTechs[$techID][$levelID] = array('tech'=> $row["tech_name"], 'name' => $row["level_name"], 'count' => intval($row["orders"]) );

                }
                //print "<pre>";
                //var_dump($arrGroupTechs);die;

                return $arrGroupTechs;

            }
            else{
                return array();
            }
        }
        else{
            return array();
        }

    }




    public function getTopByRelapseOrders($from, $to, $filterOperator, $filterBrand){

        $strFilter = $this->myFilter($filterOperator, $filterBrand);

        //u.username
        $sql = "    SELECT 	COUNT(DISTINCT(ro.id)) myCount, CONCAT(u.name, ' ', u.last_name ) username, u.id user_id
                    FROM	repair_order ro
                        INNER JOIN repair_order_fix rof ON (rof.repair_order_id = ro.relapse_repair_order_id)
                        INNER JOIN user u ON(u.id = rof.assigned_to)
                    WHERE   ro.repair_entry_type_id = 3
                    AND     (DATE(ro.created_at) >= '{$from}' AND DATE(ro.created_at) <= '{$to}')
                    {$strFilter}
                    GROUP BY u.id
                    ORDER BY myCount DESC
                    LIMIT 30;";

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $execute = $stmt->fetchAll();

        if(!empty($execute)){
            return $execute;
        }
        else{
            return array();
        }


    }
    
		
}
