<?php

namespace Solucel\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	


    public function getRequiredDTData($start, $length, $orders, $search, $columns, $userFilters)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('u');

        // Create Count Query
        $countQuery = $this->createQueryBuilder('u');
        $countQuery->select('COUNT(u)');

        // Create inner joins
        $query->join('u.role', 'r');
        $countQuery->join('u.role', 'r');

        //filter brand
        if($userFilters["brand_id"] != NULL){
            $query->andWhere('u.deviceBrand = '.intval($userFilters["brand_id"]));
            $countQuery->andWhere('u.deviceBrand = '.intval($userFilters["brand_id"]));
        }

        if($userFilters["center_id"] != NULL){
            $query->andWhere('u.serviceCenter = '.intval($userFilters["center_id"]));
            $countQuery->andWhere('u.serviceCenter = '.intval($userFilters["center_id"]));
        }

        if($userFilters["operator_id"] != NULL){
            $query->andWhere('u.operator = '.intval($userFilters["operator_id"]));
            $countQuery->andWhere('u.operator = '.intval($userFilters["operator_id"]));
        }


        //ENABLED
        $query->andWhere("u.enabled = 1");
        $countQuery->andWhere("u.enabled = 1");
        //$query->andWhere("r.enabled = 1");
        //$countQuery->andWhere("r.enabled = 1");



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'u.id ='. $searchItem;
                        break;
                    }
                    case 'username':
                    {
                        $searchQuery = 'u.username LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'role':
                    {
                        $searchQuery = 'r.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'name':
                    {
                        $searchQuery = 'u.name LIKE \'%'.$searchItem.'%\'';
                        $searchQuery .= ' OR u.lastName LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'email':
                    {
                        $searchQuery = 'u.email LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'u.id';
                        break;
                    }

                    case 'email':
                    {
                        $orderColumn = 'u.email';
                        break;
                    }

                    case 'role':
                    {
                        $orderColumn = 'r.name';
                        break;
                    }

                    case 'name':
                    {
                        $orderColumn = 'u.name';
                        break;
                    }

                    case 'enabled':
                    {
                        $orderColumn = 'u.enabled';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }
	
	public function getUserFilters($userID, $serviceID){
		//die;
		
		$strFilter = "";
		if($serviceID != 0){
			$strFilter = " AND sc.id = $serviceID";
		}
		
		
			$sql = "	SELECT 	brand.id brand_id, brand.name brand_name, 
								sc.id center_id, sc.name center_name,
								o.id operator_id, o.name operator_name
								
						FROM	user u
							LEFT JOIN device_brand brand ON ( u.device_brand_id = brand.id )
							LEFT JOIN service_center sc ON ( u.service_center_id = sc.id )
							LEFT JOIN operator o ON ( u.operator_id = o.id )
						
						WHERE		u.enabled = 1 
						{$strFilter}";
						//WHERE	u.id = '{$id}'
	
					 
		   
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
	    $stmt->execute();
		
	    $execute = $stmt->fetchAll();
	    				   

		return $execute[0];		
		
		
	}
	
		
}
